package bean.model;
// Generated 25-feb-2016 13:23:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoriaprofesional generated by hbm2java
 */
public class Categoriaprofesional  implements java.io.Serializable {


     private Integer codCategoriaP;
     private Contrato contrato;
     private String catNombre;
     private Set<Nomina> nominas = new HashSet<Nomina>(0);

    public Categoriaprofesional() {
    }

	
    public Categoriaprofesional(Contrato contrato, String catNombre) {
        this.contrato = contrato;
        this.catNombre = catNombre;
    }
    public Categoriaprofesional(Contrato contrato, String catNombre, Set<Nomina> nominas) {
       this.contrato = contrato;
       this.catNombre = catNombre;
       this.nominas = nominas;
    }
   
    public Integer getCodCategoriaP() {
        return this.codCategoriaP;
    }
    
    public void setCodCategoriaP(Integer codCategoriaP) {
        this.codCategoriaP = codCategoriaP;
    }
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }
    public String getCatNombre() {
        return this.catNombre;
    }
    
    public void setCatNombre(String catNombre) {
        this.catNombre = catNombre;
    }
    public Set<Nomina> getNominas() {
        return this.nominas;
    }
    
    public void setNominas(Set<Nomina> nominas) {
        this.nominas = nominas;
    }




}


