package bean.model;
// Generated 25-feb-2016 13:23:15 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contrato generated by hbm2java
 */
public class Contrato  implements java.io.Serializable {


     private Integer codContrato;
     private Date contFechaInicio;
     private Date contFechaFin;
     private Set<Categoriaprofesional> categoriaprofesionals = new HashSet<Categoriaprofesional>(0);

    public Contrato() {
    }

	
    public Contrato(Date contFechaInicio) {
        this.contFechaInicio = contFechaInicio;
    }
    public Contrato(Date contFechaInicio, Date contFechaFin, Set<Categoriaprofesional> categoriaprofesionals) {
       this.contFechaInicio = contFechaInicio;
       this.contFechaFin = contFechaFin;
       this.categoriaprofesionals = categoriaprofesionals;
    }
   
    public Integer getCodContrato() {
        return this.codContrato;
    }
    
    public void setCodContrato(Integer codContrato) {
        this.codContrato = codContrato;
    }
    public Date getContFechaInicio() {
        return this.contFechaInicio;
    }
    
    public void setContFechaInicio(Date contFechaInicio) {
        this.contFechaInicio = contFechaInicio;
    }
    public Date getContFechaFin() {
        return this.contFechaFin;
    }
    
    public void setContFechaFin(Date contFechaFin) {
        this.contFechaFin = contFechaFin;
    }
    public Set<Categoriaprofesional> getCategoriaprofesionals() {
        return this.categoriaprofesionals;
    }
    
    public void setCategoriaprofesionals(Set<Categoriaprofesional> categoriaprofesionals) {
        this.categoriaprofesionals = categoriaprofesionals;
    }




}


