package bean.model;
// Generated 25-feb-2016 13:23:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private Integer codDepartamento;
     private Empleado empleado;
     private String dptoNombre;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Departamento() {
    }

	
    public Departamento(Empleado empleado, String dptoNombre) {
        this.empleado = empleado;
        this.dptoNombre = dptoNombre;
    }
    public Departamento(Empleado empleado, String dptoNombre, Set<Empleado> empleados) {
       this.empleado = empleado;
       this.dptoNombre = dptoNombre;
       this.empleados = empleados;
    }
   
    public Integer getCodDepartamento() {
        return this.codDepartamento;
    }
    
    public void setCodDepartamento(Integer codDepartamento) {
        this.codDepartamento = codDepartamento;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getDptoNombre() {
        return this.dptoNombre;
    }
    
    public void setDptoNombre(String dptoNombre) {
        this.dptoNombre = dptoNombre;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


